name: Adicionar Mod
description: Solicitar adição de um novo mod à lista de traduções
title: "[Novo Mod]: "
labels:
  - adicionar-mod
body:
  - type: input
    id: nome_mod
    attributes:
      label: Nome do Mod
      description: Nome amigável do mod que será exibido
      placeholder: FTB Teams
    validations:
      required: true

  - type: input
    id: id_mod
    attributes:
      label: ID do Mod no Modrinth
      description: Parte final da URL no Modrinth
      placeholder: ftb-teams
    validations:
      required: true

  - type: markdown
    attributes:
      value: >-
        O mod será adicionado automaticamente ao `mods.json`.

