name: Atualizar Mods

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todos os dias às 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Instalar locale pt_BR
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
          export LANG=pt_BR.UTF-8

      - name: Executar script Python
        run: python Tradução.py

      - name: Commit e Push de alterações
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m "Atualização: $(date +'%Y-%m-%d')" || echo "Sem mudanças"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/Ezequiel9898/trad-mod.git
